### ISSUE TITLE
See if branch can be split off to a fork

### ISSUE THREAD

**Issue by merrygoat** [MechMicroMan/DefDAP#27]

**Comment by rhysgt** [comment]
This branch significantly slows GitHub Desktop when first loading the repository. I propose that we download the branch and archive it somewhere for the time being?

**Comment by mikesmic** [comment]
https://stackoverflow.com/questions/20450537/how-to-turn-a-git-branch-into-fork

Doesn't seem that hard to move it to a separate repo. Should we do that?

**Comment by rhysgt** [comment]
Have copied both of Allan's branches to a new private repo: https://github.com/MechMicroMan/DefDAP-allan

From what I can gather, the new features he implemented are:
- improved Hough transform for slip band detection (see HoughTransformExample.ipynb)
- KAM with NxN size kernel (see calculateKamNxN.ipynb)
- new grain level analysis with proxigram (see grainLevelAnalysisNotebook.ipynb)
- misorientation analysis with different reference points (see referenceOrientationNotebook.ipynb)
- Taylor factor calculation (see taylorFactorSchmidFactorNotebook.ipynb)

We should try to get these into DefDAP if possible

Already incorporated into DefDAP from what I can tell:
- IPF plotting (see ipfExample.ipynb)
