### ISSUE TITLE
Set up read the docs integration, update docs readme.

### ISSUE THREAD

**Issue by merrygoat** [MechMicroMan/DefDAP#28]

**Comment by rhysgt** [comment]
This is public now, so we can look to get readthedocs integration, and to develop the documentation some more

**Comment by rhysgt** [comment]
I've used GitHub Pages to accomplish this, so when we next push develop -> master, we should have a page at mechmicroman.github.io/defdap.

**Comment by merrygoat** [comment]
That's great. As I see it, that is equivalent to read the docs. If anything slightly superior since it is all in the same github ecosystem.
