### ISSUE TITLE
Improving file io

### ISSUE THREAD

**Issue by merrygoat** [MechMicroMan/DefDAP#47]
In preparation for use with the beta reconstruction project I would like to work on some enhancements to the file io in defdap.

As a first step I have refactored the tests to make them a lot more readable. I have also greatly decreased the size of the test files. I am working in the io branch.

My proposals for improvement are:

- Add ability to write CTF
- Add ability to write CRC/CPR
- Add a universal load_ebsd(fileName) method which calls the relevant loader depending on the file extension of the file name
- Look into the possibility of a more fleshed out EBSD data object with instance variables - at the moment the object is just a container with dictionaries

Do let me know if you have any other requirements/restrictions/thoughts and i'll include them.

**Comment by merrygoat** [comment]
OK I see the Map class now. I am going to take the file reading logic out of there and put it in the reader class. This way the Map is independent of the reading - we shouldn't have to change the Map class if we want to implement a new file reader.

**Comment by mikesmic** [comment]
Those improvements all sound good. After that we need to think how best to deal with maps that have more than 1 phase, @rhysgt has done a little bit on this already.

The dictionaries in the file_readers module are just used for moving the loaded raw data into the map object which then uses what it needs and then discards the rest I think.

**Comment by merrygoat** [comment]
I've simplified the reading and removed the intermediate loader object by populating the Map from the loader directly. 

Just got to write the writing methods now.

**Comment by merrygoat** [comment]
I've realised that it doesn't make sense to output CTF files since only half of the experimental data is read in from the CTF. It is not experimental data that DefDap outputs, it is an analysis which is likely represented by an image of some kind...

**Comment by JQFonseca** [comment]
I think this is why we should be able to import the whole thing and
preserve as much of the other data as possible, just swapping phase and
Euler angles.

We would like CTF files so we can import the data into MTEX to do
further analysis, for example.

**Comment by merrygoat** [comment]
OK then, I will do writers. I had a good chat with Mike about various options and will start by filling in the absent information with blanks - I'm keen not to modify the core EBSD object for now.

I've got a copy of channel 5 now so can also check the output works with that too.

**Comment by JQFonseca** [comment]
Sure, sounds good. Instead of loading everything into the EBSD object, we
could just keep an index of the position of each point in the file and then
re-read the original file at the end and just replace the alpha Euler
angles with the new calculated values (and change phase ID).

João
