### ISSUE TITLE
Conda environment file

### ISSUE THREAD

**Issue by JQFonseca** [MechMicroMan/DefDAP#57]
Could we create a conda environment file that can run the current version? We have a lot of dependencies and it would be nice to install them all in one go. There might also be a better way of doing this.

**Comment by mikesmic** [comment]
I'm not sure this is necessary, when you install with pip it will install any missing dependencies fro you. Also the majority of the dependencies are included in a standard anaconda install and the others (matplotlib_scalebar, peakutils, networkx) are only available through pip I think.

What will a conda environment file add?

**Comment by aplowman** [comment]
The way I use conda `environment.yml` (and pip `requirements.txt`) files is to list any additional tools required for development, which may or may not be applicable in this case. For general users, sticking everything in `setup(install_requires=[...], ...)` as you've done is best I think.

(As an aside, you can include pip packages in conda environment files like this:

```yml
name: my_env
dependencies:
- python > 3.7
- pip
- pip:
  - package_from_pip_1
  - package_from_pip_2
```
)

**Comment by JQFonseca** [comment]
Sorry, it tink this is fine. It didn't work for me because I thought I had installed but it asked me to install dependencies but that was because I had installed it on my laptop (no broken) and not on this one. I agree, what you are doing is good!

**Comment by mikesmic** [comment]
> The way I use conda `environment.yml` (and pip `requirements.txt`) files is to list any additional tools required for development, which may or may not be applicable in this case. For general users, sticking everything in `setup(install_requires=[...], ...)` as you've done is best I think.
> 
> (As an aside, you can include pip packages in conda environment files like this:
> 
> ```yaml
> name: my_env
> dependencies:
> - python > 3.7
> - pip
> - pip:
>   - package_from_pip_1
>   - package_from_pip_2
> ```
> 
> )

I like the idea of having a separate environment to develop in but with defdap depending on some very large packages practically I can't waste that much space having several installs of them
