### ISSUE TITLE
Warning when loading DefDap

### ISSUE THREAD

**Issue by JQFonseca** [MechMicroMan/DefDAP#63]
I got a warning on loading DefDaf:

/home/joao/Dropbox (Research Group)/shared with João/RDR/defdap/DefDAP/defdap/plotting.py:699: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.plotType is "log":

This is a new warning in python 3.8 but looks like one we should fix:

https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

**Comment by rhysgt** [comment]
I had a quick look though and I think this issue is only arises in a couple of lines in the function that you mentioned in the `HistPlot` class. I will fix now

**Comment by rhysgt** [comment]
Fixed in 1aa75ec
