### ISSUE TITLE
Change the way EBSD data is linked to a DIC map

### ISSUE THREAD

**Issue by rhysgt** [MechMicroMan/DefDAP#68]
Currently, a flood-fill algorithm is used to detect grains (defined from an EBSD map) into the DIC map. 

An alternative way of doing this, is warping the EBSD grain map directly using the affine (or polynomial etc) transform. Attached is an example of the EBSD grain list, current DIC grain list and my proposed method. It has a few advantages
- Very fast (pretty much instantaneous)
- Deals with non-indexed points better
- EBSD and DIC grains have the same ID number

Since this would be quite a big change, would be a good to get opinions on it and test it before implementing it.

![image (1)](https://user-images.githubusercontent.com/19435305/89522429-22351280-d7d9-11ea-9d6b-b4969108b867.png)

**Comment by rhysgt** [comment]
Have implemented this in the new_dic_grain_detection branch. Have tested with a couple of datasets and works well. The DIC and EBSD grain IDs are not the same (I've made the DIC grain IDs sequential) however the EBSD grain is unambiguously defined within the DIC grain.

**Comment by mikesmic** [comment]
This is great if we can perform the grain linking in a more direct way. However, with this being a central part of the package we should try and add some testing to the current process and see how this will change with the modifications

**Comment by rhysgt** [comment]
Sounds reasonable. I mainly implemented this for my benefit but hopefully it will help others when fully tested :)

I have set the default algorithm to be the same as it is currently. To use the new algorithm, set `algorithm` to `warp`. I'll work on the timeseries a little bit now

**Comment by rhysgt** [comment]
Pretty happy that this works pretty reliably now so will close the issue for now.
