### ISSUE TITLE
Filtering of data

### ISSUE THREAD

**Issue by rhysgt** [MechMicroMan/DefDAP#70]
I have implemented a basic filtering algorithm in the filtering branch, which I have personally used. It's very basic but works well. It is based on simple thresholding of effective shear strain values, then binary dilation of the mask to ensure all erroneous data points are removed. I set these values to NaN, which works fine with current DefDAP functions, maybe not the RDR calculations.

I would be interested to hear if others might have a better method and the strategy for this in future.

**Comment by mikesmic** [comment]
Wrote this just looking at the commit:

I like the idea of having masking, I can see lots of uses for it and this first implementation is a good start. However, I don't think the values in the data should be set to nan except maybe in the case of removing spurious data with bad correlation value. I think it would be better to use property getter methods to apply mask when the data is accessed, maybe the data fields need be abstracted to allow this to be done easily for original data and any derived fields. It's also worth looking into using numpy masked arrays, as I'm sure they'll be very efficient and be interoperable with functions in numpy and the rest of the scipy stack.

But as you've said here it's just for removing erroneous data then what you've done is great. It would be good to have an option to filter based on loaded correlation value as well, I might update to do this if I get time. I think this and cropping cover most of what is needed for now. So above is just some thoughts for if we ever want/need to make a more general purpose implementation of masking.

**Comment by rhysgt** [comment]
Yup, I agree using numpy masked arrays would be better, but would require more work - something to do in future. For my purposes, this works great for the time being. Changing it to mask based on correlation value is trivial as well. Additionally, it's somewhat extensible, in that you can define a mask manually (by setting dicMap.mask) and apply it using applyThresholdMask. Actually, that function should probably be called applyMask...

**Comment by hakonanes** [comment]
You might be interested in looking at the approach in orix' `CrystalMap` class where an attribute `is_in_data`, a boolean array, works as this mask. The mask is set either [upon initialization](https://github.com/pyxem/orix/blob/master/orix/crystal_map/crystal_map.py#L198) or whenever only a subset of points are returned from [`CrystalMap.__getitem__()`](https://github.com/pyxem/orix/blob/master/orix/crystal_map/crystal_map.py#L403), say when only one phase's points should be returned with `xmap_ferrite = xmap["ferrite"]`, or points should be thresholded by some value `xmap_high_bc = xmap[xmap.bc >= 0.5]`. The attribute is part of the public API, so the user can set it directly themselves if they want to.

All `CrystalMap` attributes storing value(s) per point, like `rotations` (quaternions) or any property, are masked when the `getter` is called, like `xmap_high_bc.bc` only returns those points higher than 0.5. The map's shape is still maintained, so plotting can be done, with masked out values white (or whatever color or value you provide to the plotting method).
