### ISSUE TITLE
Error when using grain inspector for cubic materials

### ISSUE THREAD

**Issue by davidlunt88** [MechMicroMan/DefDAP#83]
<img width="1088" alt="Screenshot 2021-04-15 at 14 52 35" src="https://user-images.githubusercontent.com/19265444/114883026-711d5800-9dfc-11eb-9783-54096dfe8066.png">

After installing the latest version DefDAP, when running grain inspector for cubic materials I get a "name 'quatToPlot' is not defined" error. I have just tried again on an older version and works perfectly.

**Comment by rhysgt** [comment]
Fixed in 6808ef1
Didn't test unit cell plotting in cubic but now works

**Comment by rhysgt** [comment]
Fixed another bug in 201c3ed
Should be good now
