### ISSUE TITLE
Errors when using the advanced_notebook

### ISSUE THREAD

**Issue by sh17253** [MechMicroMan/DefDAP#86]
Got the error when running the cells in the advanced_notebook..

![issue](https://user-images.githubusercontent.com/75548632/115548644-9ea44e80-a29f-11eb-82ca-a953e1c78a77.JPG)

**Comment by rhysgt** [comment]
Hi sh17253,

I've not seen this issues before. Have you run all the cells prior to this one? Could you also update defdap to the latest version using `pip install defdap` if it's not already?
