### ISSUE TITLE
Questions about EBSD analyses in Defdap

### ISSUE THREAD

**Issue by jluo28** [MechMicroMan/DefDAP#89]

**Comment by jluo28** [comment]
Hi all,

I have 2 questions about EBSD analyses in Defdap.

 1) I found there is a class for linking multiple EBSD maps (i.e. ebsd. Linker) in defdap, and this is exactly what I want to use for my data analyses. What I want to do is to align the EBSD maps at several deformation stages. I had a go myself with the code provided in API documentation but failed to get the results I expect. Below is a screenshot of my code, there are no errors when I run the code but I also don't think I've successfully linked these 2 ebsd maps. I expect that after the linking, the grains in the 2nd ebsd map will have the same IDs as that in the 1st ebsd.  Could anyone give me some advice on how I should modify/add code for this? Or did I misunderstand the code shown in the documentation and they won't work in this way?
    
    ![image](https://user-images.githubusercontent.com/88724049/129312975-e764fe37-50a8-409d-a157-636111550929.png)
  
2) I'm working on multiphase steels and for some of the analyses, I want to study only one phase, would it be possible for Defdap to only analyse one phase for multiphase material? for example, only plot IPF for one phase, only show the grain ID for one phase, only show max shear strain for one phase etc. 

Any advice is much appreciated!

Thanks,
Jie

**Comment by mikesmic** [comment]
Hi Jie,

The EBSD linker class is a very old feature that I never really took the time to keep up to date when making changes to the core parts of the library. I can't exactly remember how it worked but it was quite manual I think, it would cycle through every grain in the first map, guess the corresponding grain in the other maps based on the location and then ask you to confirm that it guessed correctly. I will have a look through the code and try and make it work again for you when I have a chance.

For your second question, the multiphase analysis features are a newish addition and not really complete. Some of what you list is possible, here are some snippets of code for you to try:

```
# print phases in your map
for i, phase in enumerate(ebsdMap.phases):
    print(f'ID: {i}')
    print(phase)
    print()
```
```
# Set the primary phase, used in functions not changed 
# to work with multiple phases
ebsdMap.primaryPhaseID = 0
```
```
# pass a list of phase ID. Will work for multiple
# and the correct symmetry will be used for each
ebsdMap.plotIPFMap([0,0,1], phases=[0])
```
```
phase_id = 0
# Change primary phase so correct symmetry used in 
ebsdMap.primaryPhaseID = phase_id
# Filter grains based on phase id 
dic_grain_ids = [grain.grainID for grain in dicMap 
                 if grain.ebsdGrain.phaseID == phase_id]
# Plot in an IPF
dicMap.plotGrainDataIPF([0,0,1], mapData=dicMap.crop(dicMap.eMaxShear), 
                        grainIds=dic_grain_ids, marker='o')
```

Let me know if you want me to explain the code in more detail, I ran this in these in the example notebook using the example data. We can discuss further If you have specific type of plot you want to produce

**Comment by jluo28** [comment]
Hi Michael,

Thank you very much for the reply. This is really helpful to me! I tried the code you provided and it worked well with the IPF colouring map and plotting grains in an IPF. The code looks very clear so I understand how it works. I have just one more question, now that we found the grainIDs of one phase, is it possible for Defdap to only plot these grain numbers rather than all the grain numbers in a dic map? 

I tried `plot.addGrainNumbers()`, but this would plot all the grain IDs on the map. 

I also have a follow-up question for the last issue I posted here. I cleaned the EBSD data and tried to load it into Defdap but I get the error below. (I did this in AztecCrystal, and when it export the CPR files, these files don't contain edx data). Is it that Defdap can only read the files containing both EBSD and EDX data? 
![image](https://user-images.githubusercontent.com/88724049/129678864-b0741c55-d1f4-4971-a0a8-0674a0adf69f.png)

Thanks,
Jie

**Comment by mikesmic** [comment]
The EBSD grain linker should be working as intended again now with the commit I made on the dev branch. Can you give this a try and let me know if you have any issues. It is quite a manual process but I can help you with improving the functionality if it is something you are interested in. Usage:

- Load in your EBSD maps and run grain detection.
- Create the grain linker with `linker = ebsd.Linker([ebsd_map_1, ebsd_map_2, ebsd_map_3])`. The first map in the list is the 'master_map'.
- Set the origin of each map with `linker.set_origin()`, this will open a figure for each map where you need to click to set a single corresponding point in each map.
- Add links between grains with `linker.start_linking()`, this will open a figure for each map. Click a grain on the 'master_map' and the code will try to guess the corresponding grain in all the other maps and highlight them. If the guess is not correct in any of the other maps then click on the correct grain in that map. When all are correct, press the make link button to save the link.

Let me know if you have questions.

**Comment by jluo28** [comment]
Hi Mike, 

Thanks very much for your instructions on this. I tried to follow your instructions above, but I still have 2 questions about it:

- After I run `linker.setOrigin()`, there are ebsd maps popping up, but no coordinates will show as outputs after I click on the maps. I'm now dealing with cleaned-up maps, not sure whether this is the reason for this. Because last week, when I loaded the maps without clean-up, I could see coordinates as outputs after I click on the maps.

     Also, if you see the Euler maps shown below, now they won't show grain boundaries anymore, and if you run `locateGrainID()` for the ebsd map, you could still click grains and the clicked grains will be highlighted, but no Grain ID shows as outputs anymore. 

![Screen Shot 2021-08-25 at 08 00 46](https://user-images.githubusercontent.com/88724049/130695922-7f2a8ee1-4484-42bd-9abf-1a44fa76a4e6.png)


- After running `linker.startLinking()`, the same error message will show up. Please see the screenshot below. 

![image](https://user-images.githubusercontent.com/88724049/130695738-f1be8f69-50d6-4b16-bb8f-1e16ab81de41.png)

Thanks,
Jie

**Comment by jluo28** [comment]
Hi Mike,

Thanks to the code you shared previously, I can now make links between several EBSD maps. This is great and I really appreciate your help. Now I'd like to link all the grains within the same region at different strain levels and track how each grain deforms.  I've been manually linking each grain and recording the grain IDs, grain properties and strains for each grain at different global strain levels. This works alright but for microstructure that has smaller grains, it could be a bit slow to analyse all the grains within the area of interest. I was wondering do you have any ideas or advice on how to link a large number of grains a bit quicker?  Hopefully I explained my thoughts clearly, and again, any ideas are much appreciated.

Cheers,
Jie

**Comment by mikesmic** [comment]
What data have you collected? Is for multiple EBSD maps or is this for HRDIC measurements. It might be best to have a call to discuss what you are trying to do and I'll try to point you in the right direction. Send me a message on slack and we can organise something.
