### ISSUE TITLE
Recent error with RDR

### ISSUE THREAD

**Issue by BenP123** [MechMicroMan/DefDAP#96]
As discussed briefly earlier, a new error has appeared with using RDR in defDAP. 

When I run the grain inspector tool I get 

`AttributeError`: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

I thought that this might be something with tk, so I swapped to using qt and still get the same error. I'm not sure if this is caused by defdap or some external package as I've tried running this with a clean conda environment with a pip install directly and by cloning the develop branch from github and installing it locally and both still give the same error.

**Comment by JQFonseca** [comment]
What's the line in DefDap that triggers this? Does the error message say?

**Comment by BenP123** [comment]
Removing the `set_window_title` works. RDR seems happy. I'll report back if removing this has broken anything else.

**Comment by rhysgt** [comment]
Fixed in [718fdad](https://github.com/MechMicroMan/DefDAP/commit/718fdad5cc726eca93b8499861f2b94506455d28)

**Comment by rhysgt** [comment]
Fixed in [718fdad](https://github.com/MechMicroMan/DefDAP/commit/718fdad5cc726eca93b8499861f2b94506455d28)
